---
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README*'
      - '.github/dependabot.yml'
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  PAGES_BASE_URL: ${{ vars.PAGES_BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.0
    steps:
      - name: Install Hugo CLI
        run: >
          wget -O ${{ runner.temp }}/hugo.deb
          https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build for GitHub Pages with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: >
          hugo
          --gc
          --minify
          --destination github_pages
          --baseURL "${{ env.PAGES_BASE_URL }}/"
      - name: Create the nojekyll file
        run: touch github_pages/.nojekyll

      - name: Build for configured base URL with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: >
          hugo
          --gc
          --minify
          --destination site

      - name: Upload artifact (GitHub Pages)
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./github_pages
      - name: Upload artifact (Site Deployment)
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./site

  gh-deploy:
    if: vars.PAGES_UPLOAD == 'true'
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Download artifact (GitHub Pages)
        uses: actions/download-artifact@v4.1.7
        with:
          name: github-pages
          path: public
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
